import React from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import FastlaneDemo from './FastlaneDemo.jsx';
import EDCardDemo from './EdCardDemo.jsx';
import ScreeningDemo from './ScreeningDemo.jsx';
const Mark=()=> <svg viewBox="0 0 72 72" aria-hidden="true"><circle cx="36" cy="36" r="31"/><path d="M18 49 36 17l18 32M24 38h24M36 17v32"/><path d="m25 50 11-9 11 9"/></svg>; const Arrow=()=> <span>↗</span>;
function App(){return <div className="app"><header><a className="brand" href="#top"><Mark/><span><b>MISHA</b><small>SYSTEMS</small></span></a><div className="badge">DEMO ENVIRONMENT</div></header><main id="top"><section className="hero"><div className="hero-glow"/><div className="container"><p className="eyebrow">MISHA SYSTEMS · EXPERIENCE PLATFORM</p><h1>Experience the future of <em>mobility.</em></h1><p className="lead">Interactive demonstrations and presentations for MISHA Systems digital mobility solutions.</p><div className="hero-actions"><a className="button primary" href="#solutions">Explore solutions <Arrow/></a><a className="button secondary" href="#fastlane-demo">Launch Fastlane demo <Arrow/></a></div></div><div className="status"><i/> DEMONSTRATION SYSTEM ONLINE</div></section><section id="solutions" className="section"><div className="container"><div className="heading"><div><p className="eyebrow">TWO CORE PRODUCTS</p><h2>See MISHA <span>in action.</span></h2></div><p>Two digital mobility solutions. One clear mission: simpler journeys and smarter border operations.</p></div><div className="cards"><article><div className="visual fastlane"><div className="gate"><span>BIOMETRIC</span><b>FASTLANE</b></div><div className="pulse"/></div><div className="body"><small>01 · eTA SOLUTION</small><h3>eTA &amp; Biometric Fastlane</h3><p>An end-to-end eTA journey with validation, parallel screening and biometric fastlane access for approved eTA applicants.</p><a href="#fastlane-demo">Launch interactive demo <Arrow/></a></div></article><article><div className="visual ed"><div className="form"><span>ED CARD</span><hr/><hr/><hr/><b>SUBMIT ARRIVAL</b></div></div><div className="body"><small>02 · DIGITAL ARRIVAL</small><h3>ED Card Portal</h3><p>A seamless digital arrival declaration journey, designed for travellers and authorities.</p><a href="#edcard-demo">Launch interactive demo <Arrow/></a></div></article></div></div></section><FastlaneDemo/><EDCardDemo/><ScreeningDemo/><section className="section architecture"><div className="container"><p className="eyebrow">MISHA PLATFORM</p><h2>Two products.<br/><span>One mobility vision.</span></h2><div className="flow"><div>eTA</div><b>+</b><div>PARALLEL SCREENING</div><b>+</b><div>BIOMETRIC FASTLANE</div><b>·</b><div>ED CARD</div></div></div></section><section className="section cta"><div className="container"><p className="eyebrow">MISHA SYSTEMS</p><h2>Ready when you are.</h2><p>For a guided demonstration, contact the MISHA Systems team.</p><a className="button primary" href="https://www.mishasystems.com/#contact">Contact MISHA Systems <Arrow/></a></div></section></main><footer><div className="container"><a className="brand" href="#top"><Mark/><span><b>MISHA</b><small>SYSTEMS</small></span></a><span>Presentation environment · © 2026 MISHA Systems</span></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
