import React from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import './architecture.css';
import './presentation.css';
import FastlaneDemo from './FastlaneDemo.jsx';
import EDCardDemo from './EdCardDemo.jsx';
import PresentationNav from './PresentationNav.jsx';
import LogoMark from './LogoMark.jsx';
const Arrow=()=> <span aria-hidden="true">↗</span>;
function App(){return <div className="app"><header><a className="brand" href="#top"><LogoMark/><span><b>MISHA</b><small>SYSTEMS</small></span></a><PresentationNav/><div className="badge">DEMO ENVIRONMENT</div></header><main id="top">
<section className="hero"><div className="hero-glow"/><div className="container"><p className="eyebrow">MISHA SYSTEMS · MOBILITY INTELLIGENCE</p><h1>Mobility Intelligence<br/>for <em>Sovereign Access.</em></h1><p className="lead">Two purpose-built digital mobility solutions, connected by one governed platform.</p><div className="hero-actions"><a className="button primary" href="#solutions">Explore solutions <Arrow/></a></div></div><div className="status"><i/> DEMONSTRATION SYSTEM ONLINE</div></section>
<section id="solutions" className="section solutions"><div className="container"><div className="heading"><div><p className="eyebrow">TWO CORE PRODUCTS</p><h2>Solutions built for<br/><span>real mobility operations.</span></h2></div><p>MISHA turns complex border and arrival workflows into clear, governed digital journeys.</p></div><div className="cards"><article className="product-card"><div className="visual fastlane"><div className="gate"><span>eTA + BIOMETRIC</span><b>FASTLANE</b></div><div className="pulse"/></div><div className="body"><small>01 · ETA &amp; BIOMETRIC FASTLANE</small><h3>eTA &amp; Biometric Fastlane</h3><p>One continuous journey from eTA application and validation through payment, <strong>parallel watchlist screening</strong>, eTA decision and passport-free biometric clearance.</p><a href="#fastlane-demo">Launch interactive journey <Arrow/></a></div></article><article className="product-card"><div className="visual ed"><div className="form"><span>ED CARD PORTAL</span><hr/><hr/><hr/><b>SUBMIT ARRIVAL</b></div></div><div className="body"><small>02 · DIGITAL ARRIVAL</small><h3>ED CARD PORTAL</h3><p>A dedicated digital arrival declaration journey connecting travellers and authorities from data capture to submission.</p><a href="#edcard-demo">Launch interactive demo <Arrow/></a></div></article></div></div></section>
<FastlaneDemo/><EDCardDemo/>
<section className="section architecture" id="architecture"><div className="container"><p className="eyebrow">PLATFORM ARCHITECTURE</p><h2>One platform.<br/><span>Three governed layers.</span></h2><p className="architecture-intro">Identity, intelligence and sovereignty are not separate products. They are the platform foundations that support both MISHA solutions.</p><div className="architecture-flow"><div className="arch-node"><b>01</b><strong>IDENTITY</strong><span>Identity, access &amp; trust</span></div><div className="arch-connector"><i/></div><div className="arch-node"><b>02</b><strong>INTELLIGENCE</strong><span>Screening &amp; decisioning</span></div><div className="arch-connector"><i/></div><div className="arch-node"><b>03</b><strong>SOVEREIGNTY</strong><span>Data, policy &amp; deployment</span></div></div><div className="architecture-products"><div><span>eTA &amp; Biometric Fastlane</span><small>Identity → Intelligence → Sovereignty</small></div><div><span>ED Card Portal</span><small>Identity → Intelligence → Sovereignty</small></div></div></div></section>
<section className="section cta"><div className="container"><p className="eyebrow">MISHA SYSTEMS</p><h2>Ready when you are.</h2><p>For a guided demonstration, contact the MISHA Systems team.</p><a className="button primary" href="https://www.mishasystems.com/#contact">Contact MISHA Systems <Arrow/></a></div></section></main><footer><div className="container"><a className="brand" href="#top"><LogoMark/><span><b>MISHA</b><small>SYSTEMS</small></span></a><span>Presentation environment · © 2026 MISHA Systems</span></div></footer></div>}
createRoot(document.getElementById('root')).render(<App/>);
